name: fast
description: An incredible command line interface for Flutter.
version: 0.5.0
homepage: https://github.com/pbissonho/fast.cli
# author: Pedro Bissonho <pedro.bissonho@gmail.com>

executables:
  fast:

environment:
  sdk: '>=2.7.2 <3.0.0'

dependencies:
  path: ^1.6.4
  args: ^1.5.2
  logger: ^0.7.0+2
  flunt_dart: ^0.4.0
  process_run: ^0.10.3
  yaml: ^2.2.1  
  http: ^0.12.1
  json2yaml: ^1.0.1
  pubspec_yaml: ^2.0.1
  plain_optional: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  test_coverage: ^0.4.1

